### ISSUE TITLE
transform报错

### ISSUE THREAD

**Issue by Dec-F** [Dec-F/picgo-plugin-watermark#1]
![image](https://user-images.githubusercontent.com/12621342/71357219-db830700-25bf-11ea-9014-ea180dd9d562.png)
试了一下报错了，我是用一张jpg图片上传的，在transform阶段报错
![bg](https://user-images.githubusercontent.com/12621342/71357247-ef2e6d80-25bf-11ea-96e5-1e13bb3b3fa5.jpg)

_Originally posted by @Molunerfinn in https://github.com/Molunerfinn/PicGo/issues/369#issuecomment-568458019_

**Comment by Dec-F** [comment]
@Molunerfinn 我这边是正常的。你发我一下你使用的PicGo，还有Node版本，我需要能复现

**Comment by Molunerfinn** [comment]
dev分支的构建版本。node版本10.15.3
![image](https://user-images.githubusercontent.com/12621342/71363913-94a00c00-25d5-11ea-8a6f-439b2fdc449d.png)

**Comment by Molunerfinn** [comment]
破案了，fontSize必须是number，建议placeholder说明一下或者内部处理一下带有`px`的字符串

**Comment by Molunerfinn** [comment]
按placeHolder的写法很容易直接写成`14px`的字符串形式

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/71366249-74c01680-25dc-11ea-81a0-1c775a71c32a.png)
测试了一下，字符串 `14` 也是OK的，那么就需要避免用户写成 `14px` 的形式了，或者内部做兼容性处理，这个issue应该可以关闭了

**Comment by Dec-F** [comment]
我做下兼容吧

**Comment by Dec-F** [comment]
@Molunerfinn  已经发了0.0.1
