### ISSUE TITLE
能否按图片的百分比打上水印标志？

### ISSUE THREAD

**Issue by zjylilin** [Dec-F/picgo-plugin-watermark#11]
不然，有些大图的比列太小了！

**Comment by Dec-F** [comment]
这个功能确实需要，但是怎么配置需要讨论一下。

直接按图片比例取值的话，比如5%，这个比例是按宽度还是高度，如果宽高比很大或者很小怎么取。

还是字体大小定个基准，比如1920对应字体大小为24px，其他尺寸按这个基准按比例缩放

**Comment by Dec-F** [comment]
需求细节确定了可以再打开
