### ISSUE TITLE
安装会失败，应该是native模块rebuild的问题

### ISSUE THREAD

**Issue by Molunerfinn** [Dec-F/picgo-plugin-watermark#3]
在PicGo的插件界面安装（dev分支的PicGo build）
![image](https://user-images.githubusercontent.com/12621342/71461563-351b4980-27eb-11ea-9b40-166524eb3f66.png)
报错，进程中断。
再次运行dev环境：
![image](https://user-images.githubusercontent.com/12621342/71461609-60059d80-27eb-11ea-9ca5-dfad9977e850.png)

我查了一下相关issue，大意就是安装build的时候，版本和electron内部的node与V8版本不一样，导致的失败。

我分析了一下，PicGo安装的时候调用的npm命令是来自于用户系统的npm命令，所以build的时候的node版本也是系统的node版本而非electron的版本。但是我们不能依赖于用户系统的node版本，所以必须插件自身跟随平台做一下兼容

查看了一下，VSCode的插件在有native模块存在的时候，也是需要预先编译多平台版本才能使用
https://github.com/Microsoft/vscode/issues/658#issuecomment-159859624

**Comment by Molunerfinn** [comment]
另外我使用nvm切换到electron的node的12.4.0版本，也依然安装失败。所以感觉插件需要预先rebuild再发布了。

**Comment by Dec-F** [comment]
不依赖系统node的。

你这个情况应该是开发环境切node版本，但是没有重新rebuild造成的

你切完node 版本，去插件目录删掉node_modules ，再npm install。 然后再启动picgo。

![image](https://user-images.githubusercontent.com/20250430/71473613-a15d7380-2812-11ea-83bb-834eb353f30e.png)
这里的版本号其实就隐含了node版本了。因为electron版本对应唯一的node版本

开发模式切换node版本其实和我上次提到的用户升级PicGo以后，插件没有重新rebuild的问题是一样的。。所以我才想要提供一个钩子，beforeLaunching之类的钩子让插件去做这个

**Comment by Molunerfinn** [comment]
我试过，直接install不行，需要自己rebuild才行

**Comment by Dec-F** [comment]
不应该啊。。我也试了。v12.13.0上添加watermark。 切换到v12.4.0。插件目录删除node_modules。yarn install后重启picgo。
我这边没报错啊

**Comment by Molunerfinn** [comment]
> 不应该啊。。我也试了。v12.13.0上添加watermark。 切换到v12.4.0。插件目录删除node_modules。yarn install后重启picgo。
> 我这边没报错啊

不是，是直接通过PicGo界面安装插件不行

**Comment by Dec-F** [comment]
我是通过界面安装的。你build出来再试试，开发模式可能有差异

**Comment by Molunerfinn** [comment]
@Dec-F 嗯build过了，也是一样的问题。我晚上回去用windows的电脑试一下看看

**Comment by Dec-F** [comment]
检查一下electron的版本，理论上Electron应用不可能依赖系统node的。
1. Electron版本没对上
2. install的时候没rebuild或者rebuild错误
3. 其他插件依赖干扰

1和3需要你再确认下。看截图信息，2应该不可能

**Comment by Molunerfinn** [comment]
1. 6.1.7是没错的，因为我是用yarn安装的，yarn.lock也是6.1.7
2. install的时候rebuild有，截图里你可以看到rebuild的输出
3. 没有其他插件，我mac开发机上的picgo没有装其他别的插件

系统的node是10.15.3

![image](https://user-images.githubusercontent.com/12621342/71475035-6e6aae00-2819-11ea-8582-9c02a5d21902.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/71475084-abcf3b80-2819-11ea-9fa2-c88e36caca0a.png)
这个就是刚用插件设置页面点击安装出现的报错

**Comment by Molunerfinn** [comment]
我稍后更新一下dev分支的代码和picgo-core的代码，你也可以测一下。

**Comment by Dec-F** [comment]
我试了，没报错。你在windows上试的结果如何

**Comment by Dec-F** [comment]
复现了

**Comment by Dec-F** [comment]
electron里安装确实是不行的。只能手动执行命令或者界面安装后去插件目录执行一次检查。

没查到相关的issues。猜测可能是rebuild本身也依赖系统，electron中的child_process可能缺少了os中child_process的某些能力。
比如
![image](https://user-images.githubusercontent.com/20250430/71508903-5865f780-28c4-11ea-82d2-daed53b8b92d.png)
![image](https://user-images.githubusercontent.com/20250430/71508905-59972480-28c4-11ea-9248-9cff513ce34a.png)


暂时解决方案我更新到readme吧，后面有别的方案再说

**Comment by Molunerfinn** [comment]
> electron里安装确实是不行的。只能手动执行命令或者界面安装后去插件目录执行一次检查。
> 
> 没查到相关的issues。猜测可能是rebuild本身也依赖系统，electron中的child_process可能缺少了os中child_process的某些能力。
> 比如
> ![image](https://user-images.githubusercontent.com/20250430/71508903-5865f780-28c4-11ea-82d2-daed53b8b92d.png)
> ![image](https://user-images.githubusercontent.com/20250430/71508905-59972480-28c4-11ea-9248-9cff513ce34a.png)
> 
> 暂时解决方案我更新到readme吧，后面有别的方案再说

赞一个

**Comment by Dec-F** [comment]
#6 
已完成内置sharp，可以尝试下，有问题统一在那个issues下反馈给我。 @Molunerfinn

**Comment by Molunerfinn** [comment]
> #6
> 已完成内置sharp，可以尝试下，有问题统一在那个issues下反馈给我。 @Molunerfinn

另外picgo有官方gitter了，欢迎随时讨论
