### ISSUE TITLE
macOS10.14.6手动安装此插件，然后PicGo无法启动

### ISSUE THREAD

**Issue by touwoyimuli** [Dec-F/picgo-plugin-watermark#4]
按照本read.md提示安装（直接在PicGo安装会失败）：
![image](https://user-images.githubusercontent.com/33887845/71624018-55983900-2c1b-11ea-8b34-4871b17676fc.png)

进行如图所示：运行`npm install picgo-plugin-watermark`命令后，重启PicGo2.1.2，然后发现无法启动成功，在启动台里里面，也是无法启动
![image](https://user-images.githubusercontent.com/33887845/71624035-7496cb00-2c1b-11ea-8ad6-99ea63069e4a.png)

安装环境：
MacOS：10.14.16
PicGo：2.1.2

**Comment by Dec-F** [comment]
需要PicGo版本在2.2.0以上的。正式版还没发，想先用的话要自己手动打包

**Comment by touwoyimuli** [comment]
刚已经卸载此低版本的插件，然后现在picGo已经可以再次启动了；
![image](https://user-images.githubusercontent.com/33887845/71624768-33a0b580-2c1f-11ea-9631-48c77fa51a0e.png)


约2-3个月前准备自己写一个上传附上水印插件的，因为之前不熟悉Electron-vue相关语言，且前面一段时间比较忙；今天晚上决心准备开始写的，然后写之前搜了一下，哦豁，发现你已经于一周前写好上传了，**表示感谢**，我就不在重复再造一个轮子了；那我等待新版本的出现(因此类的项目的自行打包不是很熟)，静候好消息
