### ISSUE TITLE
安裝后，會導致picgo無法打開

### ISSUE THREAD

**Issue by jerryc127** [Dec-F/picgo-plugin-watermark#5]
picgo v2.2.0

按照README安裝了
![image](https://user-images.githubusercontent.com/16351105/71783315-1c4b3900-3020-11ea-9622-28b5198ec061.png)
但是安裝后打不開picgo(點擊picgo無反應)
試過重啓問題依舊

**Comment by Dec-F** [comment]
感谢反馈。可以稳定复现。抱歉没在windows上单独测试。

可能需要一些时间排查问题。

**Comment by Dec-F** [comment]
@jerryc127 可以试试运行两遍`npm i picgo-plugin-watermark`
```
prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install info looking for cached prebuild @ C:\Users\46342\AppData\Roaming\npm-cache\_prebuilds\4ce218-sharp-v0.23.4-node-v64-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\46342\AppData\Roaming\npm-cache\_prebuilds\4ce218-sharp-v0.23.4-node-v64-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\46342\AppData\Roaming\picgo\node_modules\sharp\build\Release\sharp.node
prebuild-install info unpack required C:\Users\46342\AppData\Roaming\picgo\node_modules\sharp\build\Release\sharp.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```
依据日志和我测试的结果看，只有当sharp的l`lifecycle`不执行，不进行重新`prebuild`时，执行`electron-rebuild`才有效，也就是要让sharp这个包命中缓存。

但是不知道是哪里出的问题，内部实现机制我不了解，临时方案就是运行两遍`npm i picgo-plugin-watermark`。

**Comment by jerryc127** [comment]
按照你說的
安裝了2次 可以啓動程序了
但是我配置了設置（順便提個bug,這配置的設置，再重新打開時會消失），也開啓了插件
![image](https://user-images.githubusercontent.com/16351105/71827524-67765200-30db-11ea-9173-5b67f50b3ddf.png)

但是圖片上傳會報錯（通過截圖上傳）
![image](https://user-images.githubusercontent.com/16351105/71827499-50cffb00-30db-11ea-937e-a881799b6e2d.png)

把插件關閉後，再上傳，可以成功上傳

**Comment by jerryc127** [comment]
我該怎麽修正？才能加水印上傳

**Comment by Dec-F** [comment]
需要错误日志信息，在 {插件目录}/picgo.log

**Comment by Molunerfinn** [comment]
> 我該怎麽修正？才能加水印上傳

fontSize请使用`14`而不是`14px`

**Comment by Dec-F** [comment]
@Molunerfinn 应该不是这个原因，我已经做过兼容

**Comment by jerryc127** [comment]
可以了 
应该是我提的（這配置的設置，再重新打開時偶尔會消失）
这个导致

现在可以了
thx 解答

**Comment by btbsja** [comment]
请问问题解决啦吗？我运行两遍 `npm i picgo-plugin-watermark` 后插件设置并没有出现任何插件，请问是什么问题
![1](https://user-images.githubusercontent.com/56936308/75109971-4229ad00-5663-11ea-80d3-1c4999c07ad5.png)
![2](https://user-images.githubusercontent.com/56936308/75109973-43f37080-5663-11ea-9d60-743dd900e533.png)

**Comment by Molunerfinn** [comment]
> 请问问题解决啦吗？我运行两遍 `npm i picgo-plugin-watermark` 后插件设置并没有出现任何插件，请问是什么问题
> ![1](https://user-images.githubusercontent.com/56936308/75109971-4229ad00-5663-11ea-80d3-1c4999c07ad5.png)
> ![2](https://user-images.githubusercontent.com/56936308/75109973-43f37080-5663-11ea-9d60-743dd900e533.png)
> 
> PicGo版本是2.2.2 win10

你这个安装就报错了，装几次都没用。看看sharp需要装的依赖吧

**Comment by Dec-F** [comment]
#6 
已完成内置sharp，可以尝试下，有问题统一在那个issues下反馈给我。 @jerryc127 @Molunerfinn @btbsja
