### ISSUE TITLE
内置sharp模块

### ISSUE THREAD

**Issue by Dec-F** [Dec-F/picgo-plugin-watermark#6]
计划把内置一个编译好的sharp模块，解决原生模块依赖的问题。
彻底解决两个issues：
https://github.com/Dec-F/picgo-plugin-watermark/issues/5
https://github.com/Dec-F/picgo-plugin-watermark/issues/3

**Comment by Dec-F** [comment]
内置了编译好的sharp.node文件。
在mac和windows上自测通过，版本：`0.1.0-beta`。

**Comment by Molunerfinn** [comment]
npm远端依然还是0.11？

**Comment by Dec-F** [comment]
![image](https://user-images.githubusercontent.com/20250430/75154262-509dc480-5748-11ea-8348-4af0a71c7f41.png)

@Molunerfinn 指定下版本号，`npm i picgo-plugin-watermark@0.1.0-beta`

**Comment by Molunerfinn** [comment]
> ![image](https://user-images.githubusercontent.com/20250430/75154262-509dc480-5748-11ea-8348-4af0a71c7f41.png)
> 
> @Molunerfinn 指定下版本号，`npm i picgo-plugin-watermark@0.1.0-beta`

OK。另外指定版本号安装的功能2.3版本的picgo也会跟上~

**Comment by Molunerfinn** [comment]
安装测试成功。另外建议是不是应该做成一个beforeUploadPlugins的插件会更好点，我看了一下sharp不一定要读文件路径，也可以读一个buffer，这样在beforeUploadPlugins里也能实现，而且2.3里picgo增加了url上传，用的是默认的path transformer。

不过一定要做成一个transformer也是没问题的，给予了插件自由度就可以这样做，不过需要在说明里体现一下。

**Comment by Dec-F** [comment]
@Molunerfinn 了解，当初做的时候就有这个疑问，为什么path transformer的功能还要自己实现一遍。

我找时间迭代一下

**Comment by Molunerfinn** [comment]
棒，另外是不是还需要提供一份linux的内置模块，因为picgo在linux下也能跑

**Comment by Dec-F** [comment]
已完成 beforeUploadPlugins注册和linux内置sharp
