### ISSUE TITLE
每次更新picgo,都要重新安装？

### ISSUE THREAD

**Issue by jerryc127** [Dec-F/picgo-plugin-watermark#8]
每次更新picgo,都要重新安装？
刚才更新了picgo,然后显示插件没安装。。

**Comment by jerryc127** [comment]
我重新装了2次 npm install picgo-plugin-watermark
打开还是显示没安装？

**Comment by Dec-F** [comment]
#6 
已完成内置sharp，可以尝试下，有问题统一在那个issues下反馈给我。 @jerryc127
