### ISSUE TITLE
一直显示安装中

### ISSUE THREAD

**Issue by btbsja** [Dec-F/picgo-plugin-watermark#9]
win 10 ；Picgo-2.2.2
在插件设置点击安装后一直显示安装，我放置了好久都没有反应
![image](https://user-images.githubusercontent.com/56936308/75410594-62a18200-5957-11ea-8ed4-d3c16c0c9398.png)

不知道是什么问题望解答！！！！！！！！！谢谢谢谢

**Comment by Dec-F** [comment]
网速问题吧，设置一下镜像再装下试试

```bash
npm config set registry https://registry.npm.taobao.org --global
```

**Comment by btbsja** [comment]
我试过了可还是一直显示安装中，可能是我电脑自己的问题吧我再看看
![image](https://user-images.githubusercontent.com/56936308/75412022-27558200-595c-11ea-889f-89d2582eeab2.png)

**Comment by touwoyimuli** [comment]
我也遇到同样的问题，设置镜像也一样，开启全局代理模式也显示安装中（一直）。
请问下，有没有手动安装教程？

**Comment by Dec-F** [comment]
#10 
@touwoyimuli
